# This file was generated by GoReleaser. DO NOT EDIT.
class Tparallel < Formula
  desc "tparallel detects inappropriate usage of t.Parallel() method in your Go test codes"
  homepage "https://github.com/moricho/tparallel"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moricho/tparallel/releases/download/v0.1.0/tparallel_darwin_x86_64.tar.gz"
    sha256 "aad00ed49a190000839d4072a6682ee0e084ba5e1b6d1eb64d7048f19618cfde"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/moricho/tparallel/releases/download/v0.1.0/tparallel_linux_x86_64.tar.gz"
      sha256 "17c56a3014925f6668a2d4b0ca530e3e98ec96d10b57af8a7b51e9308c2a628d"
    end
  end

  def install
    bin.install "tparallel"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
